services:
  nginx:
    container_name: develop-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - SERVER_NAME=laravel-dev.boardgame.work
        - PHP_CONTAINER_NAME=develop-php
        - SSL_PORT=8443
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - ./src/public:/var/www/html/public
      - ./docker/nginx/etc/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/logs:/var/log/nginx
  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - ./docker/nginx/etc/letsencrypt:/etc/letsencrypt
      - ./src/public:/var/www/html
    command: ["--version"]
  php:
    container_name: develop-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - DEPLOY_ENV=develop
    ports:
      - 9001:9000
    volumes:
      - ./src/app:/var/www/html/app/
      - ./src/bootstrap:/var/www/html/bootstrap/
      - ./src/config:/var/www/html/config/
      - ./src/database:/var/www/html/database/
      - ./src/public:/var/www/html/public/
      - ./src/resources:/var/www/html/resources/
      - ./src/routes:/var/www/html/routes/
      - ./src/tests:/var/www/html/tests/
      - ./src/.gitignore:/var/www/html/.gitignore
      - ./src/composer.json:/var/www/html/composer.json
      - ./src/composer.lock:/var/www/html/composer.lock
      - ./src/package-lock.json:/var/www/html/package-lock.json
      - ./src/package.json:/var/www/html/package.json
      - ./src/phpunit.xml:/var/www/html/phpunit.xml
      - ./src/server.php:/var/www/html/server.php
      - ./src/vite.config.js:/var/www/html/vite.config.js
      - ./src/webpack.mix.js:/var/www/html/webpack.mix.js
  db:
    container_name: develop-db
    image: mysql:8
    env_file: ./docker/php/.env.develop
    volumes:
      - develop-db-store:/var/lib/mysql
      - ./docker/db/conf.d:/etc/mysql/conf.d
    ports:
      - 28002:3306
volumes:
  develop-db-store:
