server {
    server_name ___SERVER_NAME___;

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;

    if ($host != ___SERVER_NAME___) {
        return 403 'o';
    }

    root /var/www/html/public;
    index index.php index.html;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.(php|phar)(/.*)?$ {
        fastcgi_split_path_info ^(.+\.(?:php|phar))(/.*)$;

        fastcgi_intercept_errors on;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  PATH_INFO $fastcgi_path_info;
        fastcgi_pass   ___PHP_CONTAINER_NAME___:9000;
    }

    client_max_body_size 128M;

    location / {
        client_max_body_size 1M;
        try_files $uri $uri/ /index.php?$query_string;
    }

    ssl_certificate /etc/letsencrypt/live/___SERVER_NAME___/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/___SERVER_NAME___/privkey.pem; # managed by Certbot
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256';
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age~2592000" always;
    ssl_dhparam /etc/nginx/dhparam.pem;
}

server {
    if ($host = ___SERVER_NAME___) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;

    server_name ___SERVER_NAME___;
    return 404; # managed by Certbot
}
